### ISSUE TITLE
Initial plugin file with spaces

### ISSUE THREAD

**Issue by rfp** [log-oscon/generator-log-wp-plugin#9] opened 2017-02-08 12:42 UTC
all the other files are indented with tabs, but not the $plugin_dir/$plugin_name.php

**Comment by Narayon** [comment] 2017-08-30 12:19
I can't reproduce this problem and this should be mitigated if you have your editorconfig correctly configured.  
I'm closing this issue.

**Closed as completed** 2017-08-30 12:24 UTC
Labels: bug
